# Reinforment Learning

In [1]:
import numpy as np
import gym
import random
from IPython.display import clear_output
import time

### Setting up the environment

In [2]:
env = gym.make("FrozenLake-v0")

/home/riteshk/.local/lib/python3.5/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


### Defining the action_size and state_size

In [3]:
action_size = env.action_space.n
state_size = env.observation_space.n

### Defining the qtable

In [4]:
qtable = np.zeros((state_size, action_size))
print(qtable.shape)

(16, 4)


### Hyperparameters

In [5]:
total_episodes = 15000
learning_rate = 0.9
max_steps = 99
gamma = 0.95

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.001

### Q Learning algorithm Learning

In [6]:
# List of rewards
rewards = []

for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        exp_exp_tradeoff = random.uniform(0, 1)
     
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state, :])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        state = new_state
        if done == True:
            break
        
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)

print("Score over time: " + str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.3776
[[4.44664263e-01 7.60796603e-02 9.03847694e-02 1.29017295e-02]
 [6.61820914e-03 7.98088978e-04 9.44530681e-04 2.04634503e-01]
 [8.90372144e-04 6.59936941e-04 3.98285473e-04 8.17482941e-02]
 [2.57973475e-03 1.11478342e-03 7.82929523e-04 2.70288833e-02]
 [2.85859703e-01 3.66235826e-01 2.55211544e-02 3.67560460e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.04789784e-07 1.15863322e-12 5.90036753e-03 1.27370278e-07]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.53898986e-03 1.55505846e-02 2.97777218e-02 3.52282003e-01]
 [1.43385253e-02 5.37337350e-01 1.16858943e-03 4.75943545e-05]
 [1.42205954e-01 1.85266095e-03 7.36199729e-04 6.38850555e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.90387666e-02 6.87047567e-03 8.91722476e-01 6.25037271e-02]
 [5.85264381e-02 9.97348330e-01 2.08307914e-01 1.27586135e-01]
 [0.00000000e+00 0.00000000e+00

### Playing the game using learned qtable

In [7]:
env.reset()
rewards = []
for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)
    total_reward = 0

    for step in range(max_steps):
        clear_output(wait=True)
        env.render()
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        total_reward += reward
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            rewards.append(total_reward)
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()
print("On avgerage the reward: " + str(sum(rewards)/5))

  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 4
On avgerage the reward: 0.2
